// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackApps.Server.Data;

#nullable disable

namespace TrackApps.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241119155230_FirstMigration_InitialCreate")]
    partial class FirstMigration_InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrackApps.Server.Models.Interview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FollowUp")
                        .HasColumnType("bit");

                    b.Property<string>("InterviewDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interviewer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Round")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Interviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "CYFD",
                            ContactNumber = "",
                            InterviewDate = "2024-11-19",
                            Interviewer = "I1",
                            Position = "DB Admim",
                            Round = 1
                        },
                        new
                        {
                            Id = 2,
                            Company = "Motion Recruitment",
                            ContactNumber = "",
                            InterviewDate = "2024-11-20",
                            Interviewer = "I2",
                            Position = "Full Stack Engineer",
                            Round = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
